
extern "C" void FORTRAN_NAME(star_feedback1)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *temp, REAL *u, REAL *v,
		       REAL *w, REAL *dt, REAL *r, REAL *dx,
                       REAL *t, REAL *z,
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart,
     				 int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
             REAL *mp, REAL *tdp, REAL *tcp, REAL *te, REAL *ge,
		       int *idual);
extern "C" void FORTRAN_NAME(star_feedback2)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v,
		       REAL *w, REAL *metal,
             int *idual, int *imetal, int *imethod, REAL *dt,
		       REAL *r, REAL *dx, REAL *t, REAL *z,
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
                       REAL *sn_param, REAL *m_eject, REAL *yield,
	     int *distrad, int *diststep, int *distcells,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart,
		       int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
	     REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
	     REAL *justburn, int *crmodel, REAL *crfeedback, REAL *cr);
 
extern "C" void FORTRAN_NAME(star_feedback3mom)(int *nx, int *ny, int *nz,
						REAL *d, REAL *mu, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v,
		       REAL *w, REAL *metal, REAL *zfield1, REAL *zfield2,
	     int *idual, int *imetal, int *imulti_metals, int *imethod, 
		       REAL *dt, REAL *r, REAL *dx, REAL *t, REAL *z,
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
                       REAL *sn_param, REAL *m_eject, REAL *yield,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart,
		       int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
             REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
	     REAL *justburn, REAL *kinf, REAL *exptime);

extern "C" void FORTRAN_NAME(star_feedback3)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v,
		       REAL *w, REAL *metal, REAL *zfield1, REAL *zfield2,
	     int *idual, int *imetal, int *imulti_metals, int *imethod, 
		       REAL *dt, REAL *r, REAL *dx, REAL *t, REAL *z,
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
                       REAL *sn_param, REAL *m_eject, REAL *yield,
	     int *distrad, int *diststep, int *distcells,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart,
		       int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
             REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
			REAL *justburn, int *crmodel, REAL *crfeedback, REAL *cr);

extern "C" void FORTRAN_NAME(star_feedback5)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v, 
		       REAL *w, REAL *metal,
             int *idual, int *imetal, int *imethod, REAL *dt, 
		       REAL *r, REAL *dx, REAL *t, REAL *z, 
             REAL *d1, REAL *x1, REAL *v1, REAL *t1, REAL *yield,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart, 
		       int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
             REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type);
 
extern "C" void FORTRAN_NAME(star_feedback4)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v, 
		       REAL *w, REAL *metal,
             int *idual, int *imetal, int *imethod, REAL *dt, 
		       REAL *r, REAL *dx, REAL *t, REAL *z, 
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
                       REAL *sn_param, REAL *m_eject, REAL *yield,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart, 
		       int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
             REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type);

extern "C" void FORTRAN_NAME(star_feedback_ssn)(
    int *nx, int *ny, int *nz,
    REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v, 
    REAL *w, REAL *metal,
    int *idual, int *imetal, int *imethod, REAL *dt, 
    REAL *r, REAL *dx, REAL *t, REAL *z, 
    REAL *d1, REAL *x1, REAL *v1, REAL *t1,
    REAL *yield,
    int *nmax, REAL *xstart, REAL *ystart, REAL *zstart, 
    int *ibuff, int *level,
    REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
    REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
    int *explosionFlag, 
    REAL *smthresh, int *willExplode, REAL *soonestExplosion,
    REAL *mu,
    REAL *te1, REAL *metalIIfield, REAL *metalIIfrac, int *imetalII,
    REAL *s49_tot, int *maxlevel,
    int *distrad, int *diststep, int *distcells);

extern "C" void FORTRAN_NAME(star_feedback7)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v, 
		       REAL *w, REAL *metal,
             int *idual, int *imetal, int *imethod, REAL *dt, 
		       REAL *r, REAL *dx, REAL *t, REAL *z, 
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
                       REAL *sn_param, REAL *m_eject, REAL *yield,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart, 
		       int *ibuff, int *level,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
	     REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
			REAL *justburn, int *ctype, REAL *mbhradius);

/* adding distributed starmaker and feedback (from Norman+ 2014 and
   So+ 2014) */

extern "C" void FORTRAN_NAME(star_feedback10)(int *nx, int *ny, int *nz,
             REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v,
		       REAL *w, REAL *metal, REAL *zfield1, REAL *zfield2,
	     int *idual, int *imetal, int *imulti_metals, int *imethod, 
		       REAL *dt, REAL *r, REAL *dx, REAL *t, REAL *z,
             REAL *d1, REAL *x1, REAL *v1, REAL *t1,
                       REAL *sn_param, REAL *m_eject, REAL *yield,
	     int *distrad, int *diststep, int *distcells,
             int *nmax, REAL *xstart, REAL *ystart, REAL *zstart,
		       int *ibuff,
             REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
             REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
			REAL *justburn);

extern "C" void FORTRAN_NAME(star_feedback_pn_snia)
  (int *nx, int *ny, int *nz,
   REAL *d, REAL *dm, REAL *te, REAL *ge, REAL *u, REAL *v,
       REAL *w, REAL *metal,
   int *idual, int *imetal, int *imethod, REAL *dt,
       REAL *r, REAL *dx, REAL *t, REAL *z,
   REAL *d1, REAL *x1, REAL *v1, REAL *t1,
       REAL *sn_param, REAL *m_eject, REAL *yield,
   int *distrad, int *diststep, int *distcells,
       int *nmax, REAL *xstart, REAL *ystart, REAL *zstart, int *ibuff,
   REAL *xp, REAL *yp, REAL *zp, REAL *up, REAL *vp, REAL *wp,
       REAL *mp, REAL *tdp, REAL *tcp, REAL *metalf, int *type,
   REAL *justburn, int *iPN, int *imetalSNIa, REAL *metalSNIa);


